### PR TITLE
chore: upgrade to angular 12

### LINKED ISSUE #184: Please add support for Angular 12
Angular 12 released today, please add support for it

### PR DESCRIPTION
**Pull request by pavankjadda**
This PR upgrades library version to Angular 12 and closes #184

### CODE REVIEW

**Comment by pavankjadda** [comment]
@Napster2210 Please review and merge this PR

**Comment by pavankjadda** [comment]
@rspl-yuvraj @Napster2210 Please merge this PR

**Comment by mosheboker1** [comment]
Please review and merge there are only cosmetic changes

**Review by mosheboker1 — APPROVED** [review]

**Review by mosheboker1 — APPROVED** [review]

**Comment by indianfootballstatistics** [comment]
LGTM

**Pull request closed without merging**
